defaults:
  - base_finetune
  - /dataset: imagenet
  - /head: linear
  - /backbone: vit_dino_s

base_lr: 0.001
backbone_lr: 0.00001
num_epochs: 10
batch_size: 32
mode: LINEAR_PROBE
model_dir: ${hydra:runtime.cwd}/models/
model_tag: vit_imagenet
