defaults:
  - base_finetune
  - /dataset: tiny_imagenet
  - /head: linear
  - /backbone: vit_dino_s

base_lr: 0.001
backbone_lr: 0.00001
num_epochs: 1
batch_size: 32
mode: LINEAR_PROBE
model_dir: /models
model_tag: default
